config/routes.rb
Lepieddanslo::Application.routes.draw do
  get "welcome/contact"

  get "welcome/index"

  get "welcome/about"

  get "welcome/gallery"

  get "welcome/tarifs"

  get "welcome/book"

  root to: 'welcome#index'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def about
  end

  def gallery
  end

  def tarifs
  end

  def book
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Le Pied dans L'O</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container">
    <ul class="nav nav-tabs">
        <li><%= link_to "Home", welcome_index_path %></li>
        <li><%= link_to "About", welcome_about_path %></li>
        <li><%= link_to "Gallery", welcome_gallery_path %></li>
        <li><%= link_to "Rates", welcome_tarifs_path %></li>
        <li><%= link_to "Book", welcome_book_path %></li>
        <li><%= link_to "Contact", welcome_contact_path %></li>

    </ul>

<%= yield %>
  </div>

</body>
</html>

app/views/welcome/about.html.erb
<h1>About Le Pied dans L'O</h1>
<p>Find me in app/views/welcome/about.html.erb</p>

app/views/welcome/book.html.erb
<h1>Welcome#book</h1>
<p>Find me in app/views/welcome/book.html.erb</p>

app/views/welcome/contact.html.erb
<h1>Contact Us</h1>
<p>Find me in app/views/welcome/contact.html.erb</p>

app/views/welcome/gallery.html.erb
<h1>Welcome#gallery</h1>
<p>Find me in app/views/welcome/gallery.html.erb</p>

app/views/welcome/index.html.erb
<h1>Welcome to Le Pied dans L'O</h1>
<p>Find me in app/views/welcome/index.html.erb</p>

app/views/welcome/tarifs.html.erb
<h1>Welcome#tarifs</h1>
<p>Find me in app/views/welcome/tarifs.html.erb</p>